name: Hellow Action

on: push

jobs:
  get-configs:
    name: get/set json data
    runs-on: ubuntu-latest
    outputs:
      target: ${{steps.setting_targets.outputs.TARGETS_HELLO_LIST}}
    steps:
      - name: checkout
        uses: actions/checkout@v2.0.0
      - name: get json data
        target_list=`cat ./hello-target.json`
        TARGETS_LIST=`echo $(jq -r '.hello-target' <<< "$target_list")`
        #-----debug-----#
        echo TARGETS_LIST -> $TARGETS_LIST
        #-----debug-----#
        echo "::set-output name=TARGETS_HELLO_LIST::${{TARGETS_LIST}}"
      - id: setting_targets
  exec:
    name: build (need target)
    runs-on: ubuntu-latest
    needs: get-configs
    steps:
      - name: checkout
        uses: actions/checkout@v2.0.0
      - name: build c
        run: |
          gcc ./src/c/hello.c -o ./src/c/hello
