name: Action Samle1

on: push

jobs:

  job0:
    name: Set global env
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.setting_param.outputs.FIRST_NAME }}  #Jobのオプションに公開変数を設定することで他ジョブに公開する変数を指定できる
    steps:
      - name: checkout
        uses: actions/checkout@v2.0.0
      - name: get json param and set-output
        run: |
          politician_data=`cat ./aso.json`
          echo $politician_data
          first_name=`echo $(jq -r '.first_name' <<< "$politician_data")`
          last_name=`echo $(jq -r '.last_name' <<< "$politician_data")`
          age=`echo $(jq -r '.age' <<< "$politician_data")`
          type=`echo $(jq -r '.type' <<< "$politician_data")`
          #-----debug-----#
          echo first_name = $first_name
          echo last_name = $last_name
          echo age = $age
          echo type = $type
          #-----debug-----#
          echo "::set-output name=FIRST_NAME::$first_name"
          echo "::set-output name=LAST_NAME::$last_name"
          echo "::set-output name=AGE::$age"
          echo "::set-output name=TYPE::$type"
        id: setting_param
      - name: get param and print settings
        run: |
          my_first_name=${{ steps.setting_param.outputs.FIRST_NAME }}
          echo my_first_name is $my_first_name
          
  job1:
    name: touch and echo
    runs-on: ubuntu-latest
    needs: job0                       #job0の完了を待つ
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: make file
        run: touch sample1.txt
      - name: check file
        run: ls -l
      - name: read env
        run: echo "Job1 -> ${{ needs.job0.outputs.output1}}"
